// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_aR52Y0CtYZbtIYPi8yaz3qBntSqsBA',
    appId: '1:60505221299:web:a4a82cf54d5bd7fcdb28c6',
    messagingSenderId: '60505221299',
    projectId: 'kalmghar-947b0',
    authDomain: 'kalmghar-947b0.firebaseapp.com',
    storageBucket: 'kalmghar-947b0.firebasestorage.app',
    measurementId: 'G-E21W9FCZ2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYul5M7wKyQzX4c1l46JaQyqRVR7NL69c',
    appId: '1:60505221299:android:f8a4420e47a321d2db28c6',
    messagingSenderId: '60505221299',
    projectId: 'kalmghar-947b0',
    storageBucket: 'kalmghar-947b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJykp2MWXZpETtFgnCGiv65NyoKDiuIB8',
    appId: '1:60505221299:ios:da48578af6a8b95ddb28c6',
    messagingSenderId: '60505221299',
    projectId: 'kalmghar-947b0',
    storageBucket: 'kalmghar-947b0.firebasestorage.app',
    iosBundleId: 'com.example.kalmghar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJykp2MWXZpETtFgnCGiv65NyoKDiuIB8',
    appId: '1:60505221299:ios:da48578af6a8b95ddb28c6',
    messagingSenderId: '60505221299',
    projectId: 'kalmghar-947b0',
    storageBucket: 'kalmghar-947b0.firebasestorage.app',
    iosBundleId: 'com.example.kalmghar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg_aR52Y0CtYZbtIYPi8yaz3qBntSqsBA',
    appId: '1:60505221299:web:c623500209bef37edb28c6',
    messagingSenderId: '60505221299',
    projectId: 'kalmghar-947b0',
    authDomain: 'kalmghar-947b0.firebaseapp.com',
    storageBucket: 'kalmghar-947b0.firebasestorage.app',
    measurementId: 'G-140G928PK5',
  );

}